name: Nodechat CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  connection-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Download Go modules
        run: go mod download

      - name: Build project
        run: go build -o nodechat ./cmd/peer

      - name: Start Alice in background
        run: |
          ./nodechat --port=3001 --username=Alice --api-port=8081 &

      - name: Start Bob in background
        run: |
          ./nodechat --port=3002 --username=Bob --api-port=8082 --connect=127.0.0.1:3001 &

      - name: Wait for servers to start
        run: sleep 5

      - name: Post test message to Alice
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"type":"chat","sender":"GitHubCI","content":"Hello from GitHub Actions"}' \
          http://127.0.0.1:8081/messages

      - name: Check message retrieval
        run: |
          curl http://127.0.0.1:8081/messages
