name: Nodechat CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  connection-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Download Go modules
        run: go mod download

      - name: Build project
        run: go build -o nodechat ./cmd/peer

      - name: Start peers and test
        shell: bash
        run: |
          # Start Alice (API port=8081)
          ./nodechat --port=3001 --username=Alice --api-port=8081 &
          
          # Start Bob (API port=8082), connecting to Alice
          ./nodechat --port=3002 --username=Bob --api-port=8082 --connect=127.0.0.1:3001 &
          
          # Give them time to start listening
          sleep 5
          
          # Post a message to Alice’s API
          curl -v -X POST -H "Content-Type: application/json" \
            -d '{"type":"chat","sender":"GitHubCI","content":"Hello from GitHub Actions"}' \
            http://127.0.0.1:8081/messages
          
          # Retrieve messages from Alice
          curl -v http://127.0.0.1:8081/messages
